### PR TITLE
Added mergesort and quicksort

### PR DESCRIPTION
**Pull request by MadhavBahlMD**
Added the merge sort and quicksort implementation in JS

### CODE REVIEW

**Comment by akshitgrover** [comment]
@MadhavBahlMD these algorithms are already added for javascript.

**Comment by MadhavBahlMD** [comment]
No, they are'nt look closely.
image
image

**Comment by MadhavBahlMD** [comment]
I created a folder in each for javascript implementation of these algorithms. 👍

**Comment by akshitgrover** [comment]
I saw some other files then,
Sorry.

**Comment by ZoranPandovski** [comment]
@MadhavBahlMD @akshitgrover If there is another implementation in the same language just add your implementation it's good to have few implementations in the same language, since everyone will solve the problem in different why :D

**Comment by MadhavBahlMD** [comment]
@ZoranPandovski
AWESOME THINKING 😄 😃 👍 👍 💯 💯

**Comment by akshitgrover** [comment]
@ZoranPandovski I am creating a PR for insertion & quicksort in python.

**Comment by MadhavBahlMD** [comment]
Awesomee go ahead 👌

**Comment by ZoranPandovski** [comment]
@MadhavBahlMD Be more kind, and share and accept the opinion of others.

**Comment by MadhavBahlMD** [comment]
What!? i just said awesome??????
Awesome means i agree with him doesn't that? @ZoranPandovski

**Pull request merged**
