### PR TITLE
Add SVM Algorithm in Python using the Sklearn

### PR DESCRIPTION
**Pull request by taneemishere**
**Fixes issue:** #2490 

**Changes:**
Added the Support Vector Machine Algorithm using the scikit learn in Python.

Please label this as Hacktoberfest so that is could be counted in my entries.

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Thanks, can you just move it to the machine_learning directory?

**Comment by taneemishere** [comment]
> Thanks, can you just move it to the machine_learning directory?

@ZoranPandovski I've added it to machine_learning directory have a look over. 
And please label it for Hacktorberfest as well, please so that I could be count as my entry.

**Comment by taneemishere** [comment]
Still waiting owner...!

**Comment by ZoranPandovski** [comment]
@taneemishere You didn't move everything to machine_learning. Please check your PR and move files

**Pull request closed without merging**
