### PR TITLE
Added dynamic programming problems in C++

### PR DESCRIPTION
**Pull request by SAY-droid427**
**Fixes issue:** 
#2403 

**Changes:**
Added dynamic programming problems in C++

### CODE REVIEW

**Comment by SAY-droid427** [comment]
Yes , I will make the changes.

**Comment by SAY-droid427** [comment]
I have committed the changes. Please review it.

**Comment by SAY-droid427** [comment]
Hey ! Could you please add the hacktoberfest-accepted label while merging this PR if you find my contribution valuable?

**Review by ZoranPandovski — APPROVED** [review]

**Comment by SAY-droid427** [comment]
Could you please add the hactoberfest-accepted label here if you find my contribution valuable?

**Pull request merged**
