### PR TITLE
Add PlayFair C

### PR DESCRIPTION
**Pull request by akshitgrover**
Play Fair Cipher implementation in C.

### CODE REVIEW

**Comment by akshitgrover** [comment]
@ZoranPandovski #60

**Comment by ZoranPandovski** [comment]
@akshitgrover Pleas add tests in another PR. Thanks

**Comment by akshitgrover** [comment]
@ZoranPandovski Can I do it tomorrow?
I have an exam, Sorry.

**Comment by ZoranPandovski** [comment]
@akshitgrover Sure. Exams are always first :)

**Comment by ZoranPandovski** [comment]
@akshitgrover Sure. Exams are always first :)

**Pull request merged**
