### PR TITLE
added bucket_sort in python

### PR DESCRIPTION
**Pull request by praabi**

### CODE REVIEW

**Comment by praabi** [comment]
hii @ZoranPandovski  sry but couldn't get you.

**Comment by ZoranPandovski** [comment]
@praabi Add your implementation here https://github.com/ZoranPandovski/al-go-rithms/tree/master/sort/bucket_sort

**Comment by praabi** [comment]
which implemementation i have to add!!

**Comment by praabi** [comment]
is this enough!!

**Comment by praabi** [comment]
or i should add anythinng else!!

**Comment by praabi** [comment]
Hello! Should I add a description for the input format and output format!!!

**Pull request merged**
