### PR TITLE
File Organization Strategies.

### PR DESCRIPTION
**Pull request by codali**
File Organization strategies like 

-  Single Level  
-   Twol level
-   Hierarchial 

are added. Please Accept the pr

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Thanks @codali .You can add this comment as README, and also please move files inside operating_systems directory.

**Comment by codali** [comment]
yeah. Ok i will

**Comment by codali** [comment]
Files moved into operating-system

**Comment by ZoranPandovski** [comment]
Thanks

**Pull request merged**
