### PR TITLE
ADDED Tower-Of-Hanoi with graphical representation

### PR DESCRIPTION
**Pull request by viditvarshney**
**Fixes issue:** #1207 Added new mathematical puzzle Tower-Of-Hanoi

**Here |Tower Of HAnoi Puzzle is fully Explained WIth Graphical representation , using GIFs etc**

### CODE REVIEW

**Comment by viditvarshney** [comment]
here is a new puzzle please look at this

**Comment by ZoranPandovski** [comment]
Great, just please leave only one file inside python dir

**Comment by viditvarshney** [comment]
@ZoranPandovski  Here is only one file

**Comment by viditvarshney** [comment]
@ZoranPandovski  done

**Pull request merged**
