### PR TITLE
Group the similar characters in combinations and concatenate first and last elements alternatively

### PR DESCRIPTION
**Pull request by SaiSudhaV**
Fixes issue:
Issue no: #3266

Changes:

Added one type of lexicographical grouping
Description:

If we consider a string, group the similar characters in combinations. Then, concatenate first element and last element alternatively.

### CODE REVIEW

**Comment by SaiSudhaV** [comment]
Hello @ZoranPandovski 
Check the code and approve the changes. I'm not sure why the check is failing but the code which is being mentioned as part of the check is not part of my changes. Let me know if I have to do anything?

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Can you please provide more info, what is this and add it in the corresponding gir

**Comment by SaiSudhaV** [comment]
Basically when you pass a string it will segregate similar characters as one group. From this segregated groups we'll form a new string.

**Comment by SaiSudhaV** [comment]
As suggested I have added back in the corresponding directory

**Pull request merged**
