### PR TITLE
Added Stack data structure

### PR DESCRIPTION
**Pull request by vaibhavagarwal220**

### CODE REVIEW

**Comment by vaibhavagarwal220** [comment]
Queue data structure also added

**Comment by vaibhavagarwal220** [comment]
I didn't understand so u are saying i just have to provide the class file and not the driver

**Comment by vaibhavagarwal220** [comment]
is it fine now

**Comment by ZoranPandovski** [comment]
@vaibhavagarwal220 Yes, thanks

**Pull request merged**
