### PR TITLE
Operation on Array in C

### PR DESCRIPTION
**Pull request by Gaurisha21**
**Fixes issue:#2557** #[Mention the issue number it fixes or add the details of the changes if it doesn't has a specific issue.]

**Changes:**
*/The program performs operations like Traversing, Insertion, Search, Sort, Deletion on an Array in C Language*/

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please follow the contribution guide

**Comment by Gaurisha21** [comment]
Please let me know what have I done wrong, I am not able to understand

**Comment by ZoranPandovski** [comment]
You need to include the file to coresponding dir e.g data_structures/array ...

**Review by Isha307 — CHANGES_REQUESTED** [review]
[1.zip](https://github.com/ZoranPandovski/al-go-rithms/files/5874737/1.zip)
We can make the sorting more feasible  as we have to sort the same array but In this algorithm for sorting, it is sorting some another array.

**Comment by ZoranPandovski** [comment]
@Isha307 Please check comments on your PR. I am closing this one. @Gaurisha21 Feel free to make new PR

**Pull request closed without merging**
