### PR TITLE
Create Swapping even and odd

### PR DESCRIPTION
**Pull request by chiragvj2**
This program/algorithm will swap even and odd bits in a number

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please follow the contribution guide

**Comment by chiragvj2** [comment]
Please let me know what changes i should make?

**Comment by ZoranPandovski** [comment]
You need to add it to the corresponding dir, also you are missing the filename extension

**Comment by chiragvj2** [comment]
Only these many changes that's it?

**Comment by chiragvj2** [comment]
I guess I have added in the al-go-rithms directory which is the correct one

**Comment by chiragvj2** [comment]
I have added one file in bit manipulation directory kindly please check it

**Pull request closed without merging**
