### PR TITLE
Added LinkdList implementaion in Java

### LINKED ISSUE #2490: Add new algorithm, data structure, cipher, puzzle
Just make new PR with an algorithm, data structures, ciphers, or puzzle implementation. Language doesn't matter. Follow the structure: https://github.com/ZoranPandovski/al-go-rithms#contribution

If the implementation already exists follow the code structure and create new dir with e.g your name, 1, 2, or use your imagination :boom: :1st_place_medal:

### PR DESCRIPTION
**Pull request by 2apreety18**
**Add new algorithm, data structure, cipher, puzz** 
resolves #2490

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Please pull the latest from upstream

**Review by 2apreety18 — COMMENTED** [review]
hello @ZoranPandovski, is it okay now? 
Otherwise I'll create a new pull req again

**Comment by ZoranPandovski** [comment]
Still the same.

**Comment by 2apreety18** [comment]
okay making a new PR then closing it.

**Pull request closed without merging**
