### PR TITLE
Create Coin Change

### PR DESCRIPTION
**Pull request by chiragvj2**
This program/algorithm will find out the number of changes required for a particular cent

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please follow the contribution guide

**Comment by chiragvj2** [comment]
Please let me know what changes i should make?

**Comment by ZoranPandovski** [comment]
Add info on what this is? Move it to corresponding dir, also you are missing filename extension

**Comment by chiragvj2** [comment]
Okay

**Pull request closed without merging**
