### PR TITLE
Digital Signature Algorithm

### PR DESCRIPTION
**Pull request by harshi07**
**Fixes issue:**
#1206 (Add new Algorithm)

**Changes:**
This is Digital Signature Algorithm by making a use of RSA block cipher.

### CODE REVIEW

**Comment by harshi07** [comment]
Made changes as requested.

**Comment by ZoranPandovski** [comment]
@harshi07 You maybe forgot to push them ?

**Comment by harshi07** [comment]
Changes are made as requested.

**Comment by ZoranPandovski** [comment]
@harshi07 It's cryptography/Digital Signature/DigitalSignature.java instead of cryptography/Digital Signature/java/DigitalSignature.java

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
