### PR TITLE
AVL Tree added

### PR DESCRIPTION
**Pull request by ramanb25**

### CODE REVIEW

**Comment by ramanb25** [comment]
Heap also added.

**Comment by ZoranPandovski** [comment]
Thanks @ramanb25 . Please add new PR with README for this implementations

**Comment by arvchristos** [comment]
@ZoranPandovski  I suggest to move the c++ heap of @ramanb25 to a C folder with some modifications to have purely C logic as this implementation is more suitable to  C than C++.

**Comment by ZoranPandovski** [comment]
@arvchristos  The main idea is to leave all of the implementations as they are so everyone can learn. Please make another file with the implementation and make PR.

**Pull request merged**
