### PR TITLE
Added Java 8 implementation of Histogram Equalization

### PR DESCRIPTION
**Pull request by vn17**
For issue #271

### CODE REVIEW

**Comment by vn17** [comment]
@ZoranPandovski can you please add the hacktoberfest label to this pull request?

**Comment by ZoranPandovski** [comment]
@vn17 Np, I think hacktoberfest matches merged PR's on public repository. The label is just for better search

**Comment by vn17** [comment]
Thanks @ZoranPandovski. I am not sure but the Jenkins hacktoberfest blog [here](https://jenkins.io/blog/2017/10/06/hacktoberfest/?utm_source=DigitalOcean_Hacktoberfest2017) says this 

> Hacktoberfest project requires issues and/or pull requests to be labeled with the `hacktoberfest` label

**Comment by ZoranPandovski** [comment]
@vn17 check this:  https://hacktoberfest.digitalocean.com/
To get a shirt, you must make four pull requests between October 1–31 in any timezone. Pull requests can be to any public repo on GitHub, not just the ones we’ve highlighted. The pull request must contain commits you made yourself. Pull requests reported by maintainers as spam or that are automated will be marked as invalid and won’t count towards the shirt.

**Pull request merged**
