### PR TITLE
Fibonacci in Rust

### PR DESCRIPTION
**Pull request by Jay9596**
Implementation of Fibonacci in Rust

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Hi @Jay9596 . There is already fibonacci.rs file in Rust. Please specify different name e.g jay_fibonacci. Thanks

**Comment by Jay9596** [comment]
Hi, @ZoranPandovski.
I'll make the changes as both files have different implementation but next time please check the issue numbers before accepting the PR.
My PR #159 has conflict with PR #185

**Comment by ZoranPandovski** [comment]
Thanks @Jay9596 . Doing review for 40 PR in one hour is tricky

**Comment by Jay9596** [comment]
Checkout the new PR #211.

**Pull request closed without merging**
