### PR TITLE
Added a Data structure Deque Implementaion using C++ and Java

### PR DESCRIPTION
**Pull request by Sumit2399**
**Fixes issue:** #[Mention the issue number it fixes or add the details of the changes if it doesn't has a specific issue.]
PR for #2646 

**Changes:**Added a Data structure "Deque" implementation in Java and C++.
*/The issue is not specific. I can't fix that*/

Hoping for merge soon.Thanks!

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please move them to data_structures dir

**Comment by Sumit2399** [comment]
Ok, doing it right away.

**Comment by Sumit2399** [comment]
Directory changed.Hoping for merge soon.

**Review by ZoranPandovski — APPROVED** [review]

**Comment by Sumit2399** [comment]
Looking forward to more contributions in the future.

**Pull request merged**
